version: '3'

services:
  web:
    image: php7.4-apache:projet_symphony
    container_name: projet-php-apache
    ports:
      # local:container
      - "8081:8080"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      # Lien vers le conteneur "db" (déclaré ci-après)
      - db:db
