version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql  
    volumes:
      # Volume de la base de données
      - ./db/db-data:/var/lib/mysql      
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8083:80"

  web:
    image: php:latest
    container_name: php_web
    ports:
      # local:container
      - "8081:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - ./php/:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
