version: '3'

services:
  web:
    image: php8.2-apache
    container_name: php_web
    ports:
      # local:container
      - "8081:8080"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - ./php/:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db:db

    db:
      image: mysql:8.0.31
      volumes:
        # Volume de la base de données
        - ./db-data:/var/lib/mysql      
      environment:
        MYSQL_ROOT_PASSWORD: mysql!
        MYSQL_DATABASE: mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
      ports:
        - "3306:3306"

