version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql  
    volumes:
      # Volume de la base de données
      - ./db/db-data:/var/lib/mysql      
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8083:80"

  web:
    image: nginx:latest
    container_name: nginx-container    
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
   
  php:
    image: php:7-fpm
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
